version: '3.9'
services:
  mongodb:
    image: mongo:4.2
    restart: always
    container_name: readme-users_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: readme-users-mongo
    ports:
      - "27017:27017"
    volumes:
      - readme-users_data:/data/db
    networks:
      - readme.users

  mongodb-express:
    image: mongo-express:latest
    restart: always
    container_name: readme-users_mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/
    networks:
      - readme.users

volumes:
  readme-users_data:

networks:
  readme.users:
      driver: bridge

