version: '3.5'
services:
  readme.comments.postgres:
    image: postgres:14-alpine
    container_name: readme.comments.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: readme-comments
    ports:
      - 5434:5432
    volumes:
      - readme.postgres.comments:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d readme-comments" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - readme.comments

  readme.comments.pgadmin:
    image: dpage/pgadmin4
    container_name: readme.comments.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "89179699365@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8083:80
    networks:
      - readme.comments

volumes:
  readme.postgres.comments:

networks:
  readme.comments:
      driver: bridge
